// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(OMSDbContext))]
    [Migration("20241126073422_v001.00")]
    partial class v00100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(2764));

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(4220));

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Domain.ProductTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(4472));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(4587));

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Users", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(4732));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passworded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 26, 7, 34, 22, 277, DateTimeKind.Utc).AddTicks(4829));

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("34f93433-2247-4c72-ab60-082484ff6d45"),
                            CreatedBy = "Robel",
                            CreatedDate = new DateTime(2024, 11, 26, 7, 34, 21, 761, DateTimeKind.Utc).AddTicks(4502),
                            Email = "john.doe@example.com",
                            LastName = "Doe",
                            Name = "Robel",
                            Passworded = "$2a$11$oerTxSpksiazOW5MySwgk.klyY4QMrneZuAIH/4ehpasEmzXWhQGO",
                            PhoneNumber = "123-456-7890",
                            Role = "Admin",
                            Status = 1,
                            UpdatedDate = new DateTime(2024, 11, 26, 7, 34, 21, 761, DateTimeKind.Utc).AddTicks(4505)
                        },
                        new
                        {
                            ID = new Guid("f8cf1593-eccd-4e01-8cda-eadd268b54aa"),
                            CreatedBy = "Robel",
                            CreatedDate = new DateTime(2024, 11, 26, 7, 34, 21, 933, DateTimeKind.Utc).AddTicks(4342),
                            Email = "jane.smith@example.com",
                            LastName = "Smith",
                            Name = "Jane",
                            Passworded = "$2a$11$Gow/rkja9YsgR/AYVMPezelXIQXrjSHaaTfTxGI/fMsOArispgTM.",
                            PhoneNumber = "987-654-3210",
                            Role = "User",
                            Status = 1,
                            UpdatedDate = new DateTime(2024, 11, 26, 7, 34, 21, 933, DateTimeKind.Utc).AddTicks(4346)
                        },
                        new
                        {
                            ID = new Guid("59d91785-6ff7-4bd8-a200-aeac7f604133"),
                            CreatedBy = "Robel",
                            CreatedDate = new DateTime(2024, 11, 26, 7, 34, 22, 105, DateTimeKind.Utc).AddTicks(4721),
                            Email = "robert.brown@example.com",
                            LastName = "Brown",
                            Name = "Robert",
                            Passworded = "$2a$11$zL9o4H1r6jTpsMWR/NV9quIfHoj3Agej5pJYleidq9y2b07.da.X6",
                            PhoneNumber = "555-666-7777",
                            Role = "Manager",
                            Status = 1,
                            UpdatedDate = new DateTime(2024, 11, 26, 7, 34, 22, 105, DateTimeKind.Utc).AddTicks(4725)
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.HasOne("Domain.ProductTypes", "ProductTypes")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("Domain.ProductTypes", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
